[package]
name = "katsuba-nav"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
description = "Crate for working with zone navigation graphs"
license = "ISC"
edition = "2024"

[dependencies]
katsuba-utils = { path = "../katsuba-utils" }

serde = { workspace = true }
