[package]
name = "katsuba-executor"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
description = "Worker pool for concurrent file I/O handling"
license = "ISC"
edition = "2021"

[dependencies]
crossbeam-queue = "0.3"
enum-map = "2.7"
thiserror = "1"
threadpool = "1.8"
